language: php

php:
  - 7.4
  - 8.0

before_install:
  - SYMFONY_DEPENDENCIES=$(cat composer.json | jq '.require | to_entries[] | "\(.key):\(.value)"' | egrep -o '(symfony\/[^:]+)[^|]+\|' | egrep -o '(symfony\/[^:]+)'); for SYMFONY_DEPENDENCY in $SYMFONY_DEPENDENCIES; do composer require "${SYMFONY_DEPENDENCY}:${SYMFONY_VERSION}" --no-update; done

install: composer install --no-interaction

script:
  - composer run-coverage

env:
  global:
    - CC_TEST_REPORTER_ID=e794e2c03cab23efec6b23609401a2a1c23d3f8f4e9ef6490a8d5e978a77786d
    - SYMFONY_VERSION=^5.2

# matrix:
#   include:
#       - php: 7.3
#         env: SYMFONY_VERSION=^5.2
#       - php: 7.4
#         env: SYMFONY_VERSION=^5.2

before_script:
  - sudo pecl install mongodb
  - echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "xdebug.mode=coverage" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - mv tests/_output/coverage.xml clover.xml
  - ./cc-test-reporter after-build --coverage-input-type clover --id $CC_TEST_REPORTER_ID --exit-code $TRAVIS_TEST_RESULT

# notifications:
#   slack:
#     secure: 
