services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PhpArsenal\SalesforceOutboundMessageBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Exception,Migrations,Tests,Kernel.php,functions.php}'

  PhpArsenal\SalesforceOutboundMessageBundle\Services\Factory\OutboundMessageWsdlPathFactory:
    arguments:
      - '%arsenal_salesforce_outbound_message.wsdl_directory%'

  PhpArsenal\SalesforceOutboundMessageBundle\Services\Factory\SalesforceObjectDocumentMetadataFactory:
    arguments:
      - '%arsenal_salesforce_outbound_message.document_paths%'

  PhpArsenal\SalesforceOutboundMessageBundle\Services\Builder\SoapServerBuilder:
    arguments:
      - '%arsenal_salesforce_outbound_message.wsdl_cache%'

